# Generated by Django 2.2 on 2020-05-06 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200506_0846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(default='default.jpg', null=True, upload_to='profiles/'),
        ),
    ]
