# Generated by Django 2.2 on 2020-05-05 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='scene',
            field=models.ImageField(default='hit.png', null=True, upload_to='scenes/'),
        ),
    ]
