# Generated by Django 2.2 on 2020-05-06 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200505_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='scene',
            field=models.ImageField(default='default/hit.png', null=True, upload_to='scenes/'),
        ),
    ]
