# Generated by Django 2.2 on 2020-05-06 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200506_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='scene',
            field=models.ImageField(default='default.jpg', null=True, upload_to='news/'),
        ),
    ]
