# Generated by Django 2.2 on 2020-05-07 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_article_votes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('art', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog.Article')),
            ],
            bases=('blog.article',),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
