# Generated by Django 2.2 on 2020-05-07 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200507_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='votes',
            field=models.IntegerField(default=1),
        ),
    ]
