# Generated by Django 2.2 on 2020-05-07 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20200507_1022'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
