# Generated by Django 2.2 on 2020-05-07 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_delete_vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
